// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Student struct {
	ID          pgtype.UUID        `json:"id"`
	FirstName   string             `json:"first_name"`
	LastName    string             `json:"last_name"`
	DateOfBirth pgtype.Date        `json:"date_of_birth"`
	Email       string             `json:"email"`
	Phone       pgtype.Text        `json:"phone"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type StudentSchoolEnrollment struct {
	ID             pgtype.UUID        `json:"id"`
	StudentID      pgtype.UUID        `json:"student_id"`
	SchoolID       pgtype.UUID        `json:"school_id"`
	EnrollmentDate pgtype.Date        `json:"enrollment_date"`
	Status         string             `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}
