// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createStudent = `-- name: CreateStudent :one
INSERT INTO students (first_name, last_name, date_of_birth, email, phone)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, first_name, last_name, date_of_birth, email, phone, created_at
`

type CreateStudentParams struct {
	FirstName   string      `json:"first_name"`
	LastName    string      `json:"last_name"`
	DateOfBirth pgtype.Date `json:"date_of_birth"`
	Email       string      `json:"email"`
	Phone       pgtype.Text `json:"phone"`
}

func (q *Queries) CreateStudent(ctx context.Context, arg CreateStudentParams) (Student, error) {
	row := q.db.QueryRow(ctx, createStudent,
		arg.FirstName,
		arg.LastName,
		arg.DateOfBirth,
		arg.Email,
		arg.Phone,
	)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.DateOfBirth,
		&i.Email,
		&i.Phone,
		&i.CreatedAt,
	)
	return i, err
}

const getStudent = `-- name: GetStudent :one
SELECT id, first_name, last_name, date_of_birth, email, phone, created_at FROM students WHERE id = $1
`

func (q *Queries) GetStudent(ctx context.Context, id pgtype.UUID) (Student, error) {
	row := q.db.QueryRow(ctx, getStudent, id)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.DateOfBirth,
		&i.Email,
		&i.Phone,
		&i.CreatedAt,
	)
	return i, err
}

const listStudents = `-- name: ListStudents :many
SELECT id, first_name, last_name, date_of_birth, email, phone, created_at FROM students ORDER BY created_at DESC
`

func (q *Queries) ListStudents(ctx context.Context) ([]Student, error) {
	rows, err := q.db.Query(ctx, listStudents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Student
	for rows.Next() {
		var i Student
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.DateOfBirth,
			&i.Email,
			&i.Phone,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
