// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateStudent(ctx context.Context, arg CreateStudentParams) (Student, error)
	GetStudent(ctx context.Context, id pgtype.UUID) (Student, error)
	ListStudents(ctx context.Context) ([]Student, error)
}

var _ Querier = (*Queries)(nil)
