// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEnrollment = `-- name: CreateEnrollment :one
INSERT INTO student_school_enrollments (student_id, school_id, enrollment_date, status)
VALUES ($1, $2, $3, $4)
RETURNING id, student_id, school_id, enrollment_date, status, created_at
`

type CreateEnrollmentParams struct {
	StudentID      pgtype.UUID `json:"student_id"`
	SchoolID       pgtype.UUID `json:"school_id"`
	EnrollmentDate pgtype.Date `json:"enrollment_date"`
	Status         string      `json:"status"`
}

func (q *Queries) CreateEnrollment(ctx context.Context, arg CreateEnrollmentParams) (StudentSchoolEnrollment, error) {
	row := q.db.QueryRow(ctx, createEnrollment,
		arg.StudentID,
		arg.SchoolID,
		arg.EnrollmentDate,
		arg.Status,
	)
	var i StudentSchoolEnrollment
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.SchoolID,
		&i.EnrollmentDate,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createStudent = `-- name: CreateStudent :one
INSERT INTO students (first_name, last_name, date_of_birth, email, phone)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, first_name, last_name, date_of_birth, email, phone, created_at
`

type CreateStudentParams struct {
	FirstName   string      `json:"first_name"`
	LastName    string      `json:"last_name"`
	DateOfBirth pgtype.Date `json:"date_of_birth"`
	Email       string      `json:"email"`
	Phone       pgtype.Text `json:"phone"`
}

func (q *Queries) CreateStudent(ctx context.Context, arg CreateStudentParams) (Student, error) {
	row := q.db.QueryRow(ctx, createStudent,
		arg.FirstName,
		arg.LastName,
		arg.DateOfBirth,
		arg.Email,
		arg.Phone,
	)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.DateOfBirth,
		&i.Email,
		&i.Phone,
		&i.CreatedAt,
	)
	return i, err
}

const getEnrollment = `-- name: GetEnrollment :one
SELECT id, student_id, school_id, enrollment_date, status, created_at FROM student_school_enrollments WHERE id = $1
`

func (q *Queries) GetEnrollment(ctx context.Context, id pgtype.UUID) (StudentSchoolEnrollment, error) {
	row := q.db.QueryRow(ctx, getEnrollment, id)
	var i StudentSchoolEnrollment
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.SchoolID,
		&i.EnrollmentDate,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getStudent = `-- name: GetStudent :one
SELECT id, first_name, last_name, date_of_birth, email, phone, created_at FROM students WHERE id = $1
`

func (q *Queries) GetStudent(ctx context.Context, id pgtype.UUID) (Student, error) {
	row := q.db.QueryRow(ctx, getStudent, id)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.DateOfBirth,
		&i.Email,
		&i.Phone,
		&i.CreatedAt,
	)
	return i, err
}

const listEnrollmentsByStudent = `-- name: ListEnrollmentsByStudent :many
SELECT id, student_id, school_id, enrollment_date, status, created_at FROM student_school_enrollments WHERE student_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListEnrollmentsByStudent(ctx context.Context, studentID pgtype.UUID) ([]StudentSchoolEnrollment, error) {
	rows, err := q.db.Query(ctx, listEnrollmentsByStudent, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StudentSchoolEnrollment
	for rows.Next() {
		var i StudentSchoolEnrollment
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.SchoolID,
			&i.EnrollmentDate,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudents = `-- name: ListStudents :many
SELECT id, first_name, last_name, date_of_birth, email, phone, created_at FROM students ORDER BY created_at DESC
`

func (q *Queries) ListStudents(ctx context.Context) ([]Student, error) {
	rows, err := q.db.Query(ctx, listStudents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Student
	for rows.Next() {
		var i Student
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.DateOfBirth,
			&i.Email,
			&i.Phone,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudentsBySchool = `-- name: ListStudentsBySchool :many
SELECT DISTINCT s.id, s.first_name, s.last_name, s.date_of_birth, s.email, s.phone, s.created_at
FROM students s
JOIN student_school_enrollments e ON e.student_id = s.id
WHERE e.school_id = $1
ORDER BY s.created_at DESC
`

func (q *Queries) ListStudentsBySchool(ctx context.Context, schoolID pgtype.UUID) ([]Student, error) {
	rows, err := q.db.Query(ctx, listStudentsBySchool, schoolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Student
	for rows.Next() {
		var i Student
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.DateOfBirth,
			&i.Email,
			&i.Phone,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
