// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateEnrollment(ctx context.Context, arg CreateEnrollmentParams) (StudentSchoolEnrollment, error)
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (StudentPayment, error)
	CreateStudent(ctx context.Context, arg CreateStudentParams) (Student, error)
	GetEnrollment(ctx context.Context, id pgtype.UUID) (StudentSchoolEnrollment, error)
	GetStudent(ctx context.Context, id pgtype.UUID) (Student, error)
	ListEnrollmentsByStudent(ctx context.Context, studentID pgtype.UUID) ([]StudentSchoolEnrollment, error)
	ListPaymentsByStudent(ctx context.Context, studentID pgtype.UUID) ([]StudentPayment, error)
	ListStudents(ctx context.Context) ([]Student, error)
}

var _ Querier = (*Queries)(nil)
