// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type DomainEvent struct {
	ID            pgtype.UUID        `json:"id"`
	EventType     string             `json:"event_type"`
	SourceService string             `json:"source_service"`
	AggregateID   pgtype.UUID        `json:"aggregate_id"`
	Payload       []byte             `json:"payload"`
	OccurredAt    pgtype.Timestamptz `json:"occurred_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	Processed     bool               `json:"processed"`
}
