// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEvent = `-- name: CreateEvent :one
INSERT INTO domain_events (
    event_type, source_service, aggregate_id, payload, occurred_at
)
VALUES ($1,$2,$3,$4,$5)
RETURNING id, event_type, source_service, aggregate_id, payload, occurred_at, created_at, processed
`

type CreateEventParams struct {
	EventType     string             `json:"event_type"`
	SourceService string             `json:"source_service"`
	AggregateID   pgtype.UUID        `json:"aggregate_id"`
	Payload       []byte             `json:"payload"`
	OccurredAt    pgtype.Timestamptz `json:"occurred_at"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (DomainEvent, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.EventType,
		arg.SourceService,
		arg.AggregateID,
		arg.Payload,
		arg.OccurredAt,
	)
	var i DomainEvent
	err := row.Scan(
		&i.ID,
		&i.EventType,
		&i.SourceService,
		&i.AggregateID,
		&i.Payload,
		&i.OccurredAt,
		&i.CreatedAt,
		&i.Processed,
	)
	return i, err
}

const listUnprocessedEvents = `-- name: ListUnprocessedEvents :many
SELECT id, event_type, source_service, aggregate_id, payload, occurred_at, created_at, processed FROM domain_events
WHERE processed = FALSE
ORDER BY occurred_at ASC
`

func (q *Queries) ListUnprocessedEvents(ctx context.Context) ([]DomainEvent, error) {
	rows, err := q.db.Query(ctx, listUnprocessedEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DomainEvent
	for rows.Next() {
		var i DomainEvent
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.SourceService,
			&i.AggregateID,
			&i.Payload,
			&i.OccurredAt,
			&i.CreatedAt,
			&i.Processed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEventProcessed = `-- name: MarkEventProcessed :exec
UPDATE domain_events
SET processed = TRUE
WHERE id = $1
`

func (q *Queries) MarkEventProcessed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markEventProcessed, id)
	return err
}
