// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateEvent(ctx context.Context, arg CreateEventParams) (DomainEvent, error)
	ListUnprocessedEvents(ctx context.Context) ([]DomainEvent, error)
	MarkEventProcessed(ctx context.Context, id pgtype.UUID) error
}

var _ Querier = (*Queries)(nil)
