// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type EduflexDisbursement struct {
	ID            pgtype.UUID        `json:"id"`
	SchoolID      pgtype.UUID        `json:"school_id"`
	InvoiceID     pgtype.UUID        `json:"invoice_id"`
	Amount        pgtype.Numeric     `json:"amount"`
	DisbursedAt   pgtype.Timestamptz `json:"disbursed_at"`
	PaymentMethod string             `json:"payment_method"`
	Reference     string             `json:"reference"`
	Status        string             `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}
