// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDisbursement = `-- name: CreateDisbursement :one
INSERT INTO eduflex_disbursements (
    school_id, invoice_id, amount, payment_method, reference, status
)
VALUES ($1,$2,$3,$4,$5,$6)
RETURNING id, school_id, invoice_id, amount, disbursed_at, payment_method, reference, status, created_at
`

type CreateDisbursementParams struct {
	SchoolID      pgtype.UUID    `json:"school_id"`
	InvoiceID     pgtype.UUID    `json:"invoice_id"`
	Amount        pgtype.Numeric `json:"amount"`
	PaymentMethod string         `json:"payment_method"`
	Reference     string         `json:"reference"`
	Status        string         `json:"status"`
}

func (q *Queries) CreateDisbursement(ctx context.Context, arg CreateDisbursementParams) (EduflexDisbursement, error) {
	row := q.db.QueryRow(ctx, createDisbursement,
		arg.SchoolID,
		arg.InvoiceID,
		arg.Amount,
		arg.PaymentMethod,
		arg.Reference,
		arg.Status,
	)
	var i EduflexDisbursement
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.InvoiceID,
		&i.Amount,
		&i.DisbursedAt,
		&i.PaymentMethod,
		&i.Reference,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getDisbursement = `-- name: GetDisbursement :one
SELECT id, school_id, invoice_id, amount, disbursed_at, payment_method, reference, status, created_at FROM eduflex_disbursements WHERE id = $1
`

func (q *Queries) GetDisbursement(ctx context.Context, id pgtype.UUID) (EduflexDisbursement, error) {
	row := q.db.QueryRow(ctx, getDisbursement, id)
	var i EduflexDisbursement
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.InvoiceID,
		&i.Amount,
		&i.DisbursedAt,
		&i.PaymentMethod,
		&i.Reference,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listDisbursementsBySchool = `-- name: ListDisbursementsBySchool :many
SELECT id, school_id, invoice_id, amount, disbursed_at, payment_method, reference, status, created_at FROM eduflex_disbursements WHERE school_id = $1 ORDER BY disbursed_at DESC
`

func (q *Queries) ListDisbursementsBySchool(ctx context.Context, schoolID pgtype.UUID) ([]EduflexDisbursement, error) {
	rows, err := q.db.Query(ctx, listDisbursementsBySchool, schoolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EduflexDisbursement
	for rows.Next() {
		var i EduflexDisbursement
		if err := rows.Scan(
			&i.ID,
			&i.SchoolID,
			&i.InvoiceID,
			&i.Amount,
			&i.DisbursedAt,
			&i.PaymentMethod,
			&i.Reference,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
