// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateDisbursement(ctx context.Context, arg CreateDisbursementParams) (EduflexDisbursement, error)
	GetDisbursement(ctx context.Context, id pgtype.UUID) (EduflexDisbursement, error)
	ListDisbursementsBySchool(ctx context.Context, schoolID pgtype.UUID) ([]EduflexDisbursement, error)
}

var _ Querier = (*Queries)(nil)
