// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type School struct {
	ID           pgtype.UUID      `json:"id"`
	Name         string           `json:"name"`
	Address      pgtype.Text      `json:"address"`
	ContactEmail pgtype.Text      `json:"contact_email"`
	ContactPhone pgtype.Text      `json:"contact_phone"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
}
