// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateSchool(ctx context.Context, arg CreateSchoolParams) (School, error)
	DeleteSchool(ctx context.Context, id pgtype.UUID) error
	GetSchool(ctx context.Context, id pgtype.UUID) (School, error)
	ListSchools(ctx context.Context) ([]School, error)
	UpdateSchool(ctx context.Context, arg UpdateSchoolParams) (School, error)
}

var _ Querier = (*Queries)(nil)
