// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSchool = `-- name: CreateSchool :one
INSERT INTO schools (id, name, address, contact_email, contact_phone)
VALUES (gen_random_uuid(), $1, $2, $3, $4)
RETURNING id, name, address, contact_email, contact_phone, created_at
`

type CreateSchoolParams struct {
	Name         string      `json:"name"`
	Address      pgtype.Text `json:"address"`
	ContactEmail pgtype.Text `json:"contact_email"`
	ContactPhone pgtype.Text `json:"contact_phone"`
}

func (q *Queries) CreateSchool(ctx context.Context, arg CreateSchoolParams) (School, error) {
	row := q.db.QueryRow(ctx, createSchool,
		arg.Name,
		arg.Address,
		arg.ContactEmail,
		arg.ContactPhone,
	)
	var i School
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.ContactEmail,
		&i.ContactPhone,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSchool = `-- name: DeleteSchool :exec
DELETE FROM schools WHERE id = $1
`

func (q *Queries) DeleteSchool(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSchool, id)
	return err
}

const getSchool = `-- name: GetSchool :one
SELECT id, name, address, contact_email, contact_phone, created_at FROM schools WHERE id = $1
`

func (q *Queries) GetSchool(ctx context.Context, id pgtype.UUID) (School, error) {
	row := q.db.QueryRow(ctx, getSchool, id)
	var i School
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.ContactEmail,
		&i.ContactPhone,
		&i.CreatedAt,
	)
	return i, err
}

const listSchools = `-- name: ListSchools :many
SELECT id, name, address, contact_email, contact_phone, created_at FROM schools ORDER BY created_at
`

func (q *Queries) ListSchools(ctx context.Context) ([]School, error) {
	rows, err := q.db.Query(ctx, listSchools)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []School
	for rows.Next() {
		var i School
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.ContactEmail,
			&i.ContactPhone,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSchool = `-- name: UpdateSchool :one
UPDATE schools
SET name = $2, address = $3, contact_email = $4, contact_phone = $5
WHERE id = $1
RETURNING id, name, address, contact_email, contact_phone, created_at
`

type UpdateSchoolParams struct {
	ID           pgtype.UUID `json:"id"`
	Name         string      `json:"name"`
	Address      pgtype.Text `json:"address"`
	ContactEmail pgtype.Text `json:"contact_email"`
	ContactPhone pgtype.Text `json:"contact_phone"`
}

func (q *Queries) UpdateSchool(ctx context.Context, arg UpdateSchoolParams) (School, error) {
	row := q.db.QueryRow(ctx, updateSchool,
		arg.ID,
		arg.Name,
		arg.Address,
		arg.ContactEmail,
		arg.ContactPhone,
	)
	var i School
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.ContactEmail,
		&i.ContactPhone,
		&i.CreatedAt,
	)
	return i, err
}
