// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLedgerEntry = `-- name: CreateLedgerEntry :one
INSERT INTO ledger_entries (
    event_type, event_id, source_service,
    debit_account, credit_account,
    amount, currency, occurred_at
)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8)
RETURNING id, event_type, event_id, source_service, debit_account, credit_account, amount, currency, occurred_at, created_at
`

type CreateLedgerEntryParams struct {
	EventType     string             `json:"event_type"`
	EventID       pgtype.UUID        `json:"event_id"`
	SourceService string             `json:"source_service"`
	DebitAccount  string             `json:"debit_account"`
	CreditAccount string             `json:"credit_account"`
	Amount        pgtype.Numeric     `json:"amount"`
	Currency      string             `json:"currency"`
	OccurredAt    pgtype.Timestamptz `json:"occurred_at"`
}

func (q *Queries) CreateLedgerEntry(ctx context.Context, arg CreateLedgerEntryParams) (LedgerEntry, error) {
	row := q.db.QueryRow(ctx, createLedgerEntry,
		arg.EventType,
		arg.EventID,
		arg.SourceService,
		arg.DebitAccount,
		arg.CreditAccount,
		arg.Amount,
		arg.Currency,
		arg.OccurredAt,
	)
	var i LedgerEntry
	err := row.Scan(
		&i.ID,
		&i.EventType,
		&i.EventID,
		&i.SourceService,
		&i.DebitAccount,
		&i.CreditAccount,
		&i.Amount,
		&i.Currency,
		&i.OccurredAt,
		&i.CreatedAt,
	)
	return i, err
}

const listLedgerEntries = `-- name: ListLedgerEntries :many
SELECT id, event_type, event_id, source_service, debit_account, credit_account, amount, currency, occurred_at, created_at FROM ledger_entries
ORDER BY occurred_at DESC
`

func (q *Queries) ListLedgerEntries(ctx context.Context) ([]LedgerEntry, error) {
	rows, err := q.db.Query(ctx, listLedgerEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LedgerEntry
	for rows.Next() {
		var i LedgerEntry
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.EventID,
			&i.SourceService,
			&i.DebitAccount,
			&i.CreditAccount,
			&i.Amount,
			&i.Currency,
			&i.OccurredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLedgerEntriesByEvent = `-- name: ListLedgerEntriesByEvent :many
SELECT id, event_type, event_id, source_service, debit_account, credit_account, amount, currency, occurred_at, created_at FROM ledger_entries
WHERE event_type = $1 AND event_id = $2
ORDER BY created_at DESC
`

type ListLedgerEntriesByEventParams struct {
	EventType string      `json:"event_type"`
	EventID   pgtype.UUID `json:"event_id"`
}

func (q *Queries) ListLedgerEntriesByEvent(ctx context.Context, arg ListLedgerEntriesByEventParams) ([]LedgerEntry, error) {
	rows, err := q.db.Query(ctx, listLedgerEntriesByEvent, arg.EventType, arg.EventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LedgerEntry
	for rows.Next() {
		var i LedgerEntry
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.EventID,
			&i.SourceService,
			&i.DebitAccount,
			&i.CreditAccount,
			&i.Amount,
			&i.Currency,
			&i.OccurredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLedgerEntriesByService = `-- name: ListLedgerEntriesByService :many
SELECT id, event_type, event_id, source_service, debit_account, credit_account, amount, currency, occurred_at, created_at FROM ledger_entries
WHERE source_service = $1
ORDER BY created_at DESC
`

func (q *Queries) ListLedgerEntriesByService(ctx context.Context, sourceService string) ([]LedgerEntry, error) {
	rows, err := q.db.Query(ctx, listLedgerEntriesByService, sourceService)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LedgerEntry
	for rows.Next() {
		var i LedgerEntry
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.EventID,
			&i.SourceService,
			&i.DebitAccount,
			&i.CreditAccount,
			&i.Amount,
			&i.Currency,
			&i.OccurredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
