// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	CreateLedgerEntry(ctx context.Context, arg CreateLedgerEntryParams) (LedgerEntry, error)
	ListLedgerEntries(ctx context.Context) ([]LedgerEntry, error)
	ListLedgerEntriesByEvent(ctx context.Context, arg ListLedgerEntriesByEventParams) ([]LedgerEntry, error)
	ListLedgerEntriesByService(ctx context.Context, sourceService string) ([]LedgerEntry, error)
}

var _ Querier = (*Queries)(nil)
