// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Bank struct {
	ID           pgtype.UUID        `json:"id"`
	Name         string             `json:"name"`
	ContactEmail pgtype.Text        `json:"contact_email"`
	ContactPhone pgtype.Text        `json:"contact_phone"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type LoanDrawdown struct {
	ID           pgtype.UUID    `json:"id"`
	FacilityID   pgtype.UUID    `json:"facility_id"`
	Amount       pgtype.Numeric `json:"amount"`
	DrawdownDate pgtype.Date    `json:"drawdown_date"`
	Reference    string         `json:"reference"`
}

type LoanFacility struct {
	ID           pgtype.UUID        `json:"id"`
	BankID       pgtype.UUID        `json:"bank_id"`
	CreditLimit  pgtype.Numeric     `json:"credit_limit"`
	InterestRate pgtype.Numeric     `json:"interest_rate"`
	StartDate    pgtype.Date        `json:"start_date"`
	EndDate      pgtype.Date        `json:"end_date"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type LoanRepayment struct {
	ID         pgtype.UUID        `json:"id"`
	DrawdownID pgtype.UUID        `json:"drawdown_id"`
	Amount     pgtype.Numeric     `json:"amount"`
	PaidAt     pgtype.Timestamptz `json:"paid_at"`
	Reference  string             `json:"reference"`
}
