// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// BANKS
	CreateBank(ctx context.Context, arg CreateBankParams) (Bank, error)
	// DRAWDOWNS
	CreateDrawdown(ctx context.Context, arg CreateDrawdownParams) (LoanDrawdown, error)
	// FACILITIES
	CreateFacility(ctx context.Context, arg CreateFacilityParams) (LoanFacility, error)
	// REPAYMENTS
	CreateRepayment(ctx context.Context, arg CreateRepaymentParams) (LoanRepayment, error)
	ListBanks(ctx context.Context) ([]Bank, error)
	ListDrawdownsByFacility(ctx context.Context, facilityID pgtype.UUID) ([]LoanDrawdown, error)
	ListFacilitiesByBank(ctx context.Context, bankID pgtype.UUID) ([]LoanFacility, error)
	ListRepaymentsByDrawdown(ctx context.Context, drawdownID pgtype.UUID) ([]LoanRepayment, error)
}

var _ Querier = (*Queries)(nil)
