// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBank = `-- name: CreateBank :one
INSERT INTO banks (name, contact_email, contact_phone)
VALUES ($1,$2,$3)
RETURNING id, name, contact_email, contact_phone, created_at
`

type CreateBankParams struct {
	Name         string      `json:"name"`
	ContactEmail pgtype.Text `json:"contact_email"`
	ContactPhone pgtype.Text `json:"contact_phone"`
}

// BANKS
func (q *Queries) CreateBank(ctx context.Context, arg CreateBankParams) (Bank, error) {
	row := q.db.QueryRow(ctx, createBank, arg.Name, arg.ContactEmail, arg.ContactPhone)
	var i Bank
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ContactEmail,
		&i.ContactPhone,
		&i.CreatedAt,
	)
	return i, err
}

const createDrawdown = `-- name: CreateDrawdown :one
INSERT INTO loan_drawdowns (facility_id, amount, drawdown_date, reference)
VALUES ($1,$2,$3,$4)
RETURNING id, facility_id, amount, drawdown_date, reference
`

type CreateDrawdownParams struct {
	FacilityID   pgtype.UUID    `json:"facility_id"`
	Amount       pgtype.Numeric `json:"amount"`
	DrawdownDate pgtype.Date    `json:"drawdown_date"`
	Reference    string         `json:"reference"`
}

// DRAWDOWNS
func (q *Queries) CreateDrawdown(ctx context.Context, arg CreateDrawdownParams) (LoanDrawdown, error) {
	row := q.db.QueryRow(ctx, createDrawdown,
		arg.FacilityID,
		arg.Amount,
		arg.DrawdownDate,
		arg.Reference,
	)
	var i LoanDrawdown
	err := row.Scan(
		&i.ID,
		&i.FacilityID,
		&i.Amount,
		&i.DrawdownDate,
		&i.Reference,
	)
	return i, err
}

const createFacility = `-- name: CreateFacility :one
INSERT INTO loan_facilities (bank_id, credit_limit, interest_rate, start_date, end_date, status)
VALUES ($1,$2,$3,$4,$5,$6)
RETURNING id, bank_id, credit_limit, interest_rate, start_date, end_date, status, created_at
`

type CreateFacilityParams struct {
	BankID       pgtype.UUID    `json:"bank_id"`
	CreditLimit  pgtype.Numeric `json:"credit_limit"`
	InterestRate pgtype.Numeric `json:"interest_rate"`
	StartDate    pgtype.Date    `json:"start_date"`
	EndDate      pgtype.Date    `json:"end_date"`
	Status       string         `json:"status"`
}

// FACILITIES
func (q *Queries) CreateFacility(ctx context.Context, arg CreateFacilityParams) (LoanFacility, error) {
	row := q.db.QueryRow(ctx, createFacility,
		arg.BankID,
		arg.CreditLimit,
		arg.InterestRate,
		arg.StartDate,
		arg.EndDate,
		arg.Status,
	)
	var i LoanFacility
	err := row.Scan(
		&i.ID,
		&i.BankID,
		&i.CreditLimit,
		&i.InterestRate,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createRepayment = `-- name: CreateRepayment :one
INSERT INTO loan_repayments (drawdown_id, amount, paid_at, reference)
VALUES ($1,$2,NOW(),$3)
RETURNING id, drawdown_id, amount, paid_at, reference
`

type CreateRepaymentParams struct {
	DrawdownID pgtype.UUID    `json:"drawdown_id"`
	Amount     pgtype.Numeric `json:"amount"`
	Reference  string         `json:"reference"`
}

// REPAYMENTS
func (q *Queries) CreateRepayment(ctx context.Context, arg CreateRepaymentParams) (LoanRepayment, error) {
	row := q.db.QueryRow(ctx, createRepayment, arg.DrawdownID, arg.Amount, arg.Reference)
	var i LoanRepayment
	err := row.Scan(
		&i.ID,
		&i.DrawdownID,
		&i.Amount,
		&i.PaidAt,
		&i.Reference,
	)
	return i, err
}

const listBanks = `-- name: ListBanks :many
SELECT id, name, contact_email, contact_phone, created_at FROM banks ORDER BY created_at DESC
`

func (q *Queries) ListBanks(ctx context.Context) ([]Bank, error) {
	rows, err := q.db.Query(ctx, listBanks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Bank
	for rows.Next() {
		var i Bank
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ContactEmail,
			&i.ContactPhone,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDrawdownsByFacility = `-- name: ListDrawdownsByFacility :many
SELECT id, facility_id, amount, drawdown_date, reference FROM loan_drawdowns WHERE facility_id = $1 ORDER BY drawdown_date DESC
`

func (q *Queries) ListDrawdownsByFacility(ctx context.Context, facilityID pgtype.UUID) ([]LoanDrawdown, error) {
	rows, err := q.db.Query(ctx, listDrawdownsByFacility, facilityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LoanDrawdown
	for rows.Next() {
		var i LoanDrawdown
		if err := rows.Scan(
			&i.ID,
			&i.FacilityID,
			&i.Amount,
			&i.DrawdownDate,
			&i.Reference,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFacilitiesByBank = `-- name: ListFacilitiesByBank :many
SELECT id, bank_id, credit_limit, interest_rate, start_date, end_date, status, created_at FROM loan_facilities WHERE bank_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListFacilitiesByBank(ctx context.Context, bankID pgtype.UUID) ([]LoanFacility, error) {
	rows, err := q.db.Query(ctx, listFacilitiesByBank, bankID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LoanFacility
	for rows.Next() {
		var i LoanFacility
		if err := rows.Scan(
			&i.ID,
			&i.BankID,
			&i.CreditLimit,
			&i.InterestRate,
			&i.StartDate,
			&i.EndDate,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepaymentsByDrawdown = `-- name: ListRepaymentsByDrawdown :many
SELECT id, drawdown_id, amount, paid_at, reference FROM loan_repayments WHERE drawdown_id = $1 ORDER BY paid_at DESC
`

func (q *Queries) ListRepaymentsByDrawdown(ctx context.Context, drawdownID pgtype.UUID) ([]LoanRepayment, error) {
	rows, err := q.db.Query(ctx, listRepaymentsByDrawdown, drawdownID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LoanRepayment
	for rows.Next() {
		var i LoanRepayment
		if err := rows.Scan(
			&i.ID,
			&i.DrawdownID,
			&i.Amount,
			&i.PaidAt,
			&i.Reference,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
