// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type FinancingAgreement struct {
	ID           pgtype.UUID        `json:"id"`
	StudentID    pgtype.UUID        `json:"student_id"`
	InvoiceID    pgtype.UUID        `json:"invoice_id"`
	Principal    pgtype.Numeric     `json:"principal"`
	InterestRate pgtype.Numeric     `json:"interest_rate"`
	ServiceFee   pgtype.Numeric     `json:"service_fee"`
	TotalPayable pgtype.Numeric     `json:"total_payable"`
	TermMonths   int32              `json:"term_months"`
	StartDate    pgtype.Date        `json:"start_date"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type MonthlyInstallment struct {
	ID                pgtype.UUID        `json:"id"`
	FinancingID       pgtype.UUID        `json:"financing_id"`
	InstallmentNumber int32              `json:"installment_number"`
	DueDate           pgtype.Date        `json:"due_date"`
	Amount            pgtype.Numeric     `json:"amount"`
	Status            string             `json:"status"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}
