// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateAgreement(ctx context.Context, arg CreateAgreementParams) (FinancingAgreement, error)
	CreateInstallment(ctx context.Context, arg CreateInstallmentParams) (MonthlyInstallment, error)
	GetAgreement(ctx context.Context, id pgtype.UUID) (FinancingAgreement, error)
	ListAgreementsByStudent(ctx context.Context, studentID pgtype.UUID) ([]FinancingAgreement, error)
	ListInstallments(ctx context.Context, financingID pgtype.UUID) ([]MonthlyInstallment, error)
}

var _ Querier = (*Queries)(nil)
