// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAgreement = `-- name: CreateAgreement :one
INSERT INTO financing_agreements (
    student_id, invoice_id, principal, interest_rate, service_fee,
    total_payable, term_months, start_date, status
)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)
RETURNING id, student_id, invoice_id, principal, interest_rate, service_fee, total_payable, term_months, start_date, status, created_at
`

type CreateAgreementParams struct {
	StudentID    pgtype.UUID    `json:"student_id"`
	InvoiceID    pgtype.UUID    `json:"invoice_id"`
	Principal    pgtype.Numeric `json:"principal"`
	InterestRate pgtype.Numeric `json:"interest_rate"`
	ServiceFee   pgtype.Numeric `json:"service_fee"`
	TotalPayable pgtype.Numeric `json:"total_payable"`
	TermMonths   int32          `json:"term_months"`
	StartDate    pgtype.Date    `json:"start_date"`
	Status       string         `json:"status"`
}

func (q *Queries) CreateAgreement(ctx context.Context, arg CreateAgreementParams) (FinancingAgreement, error) {
	row := q.db.QueryRow(ctx, createAgreement,
		arg.StudentID,
		arg.InvoiceID,
		arg.Principal,
		arg.InterestRate,
		arg.ServiceFee,
		arg.TotalPayable,
		arg.TermMonths,
		arg.StartDate,
		arg.Status,
	)
	var i FinancingAgreement
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.InvoiceID,
		&i.Principal,
		&i.InterestRate,
		&i.ServiceFee,
		&i.TotalPayable,
		&i.TermMonths,
		&i.StartDate,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createInstallment = `-- name: CreateInstallment :one
INSERT INTO monthly_installments (
    financing_id, installment_number, due_date, amount, status
)
VALUES ($1,$2,$3,$4,$5)
RETURNING id, financing_id, installment_number, due_date, amount, status, created_at
`

type CreateInstallmentParams struct {
	FinancingID       pgtype.UUID    `json:"financing_id"`
	InstallmentNumber int32          `json:"installment_number"`
	DueDate           pgtype.Date    `json:"due_date"`
	Amount            pgtype.Numeric `json:"amount"`
	Status            string         `json:"status"`
}

func (q *Queries) CreateInstallment(ctx context.Context, arg CreateInstallmentParams) (MonthlyInstallment, error) {
	row := q.db.QueryRow(ctx, createInstallment,
		arg.FinancingID,
		arg.InstallmentNumber,
		arg.DueDate,
		arg.Amount,
		arg.Status,
	)
	var i MonthlyInstallment
	err := row.Scan(
		&i.ID,
		&i.FinancingID,
		&i.InstallmentNumber,
		&i.DueDate,
		&i.Amount,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getAgreement = `-- name: GetAgreement :one
SELECT id, student_id, invoice_id, principal, interest_rate, service_fee, total_payable, term_months, start_date, status, created_at FROM financing_agreements WHERE id = $1
`

func (q *Queries) GetAgreement(ctx context.Context, id pgtype.UUID) (FinancingAgreement, error) {
	row := q.db.QueryRow(ctx, getAgreement, id)
	var i FinancingAgreement
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.InvoiceID,
		&i.Principal,
		&i.InterestRate,
		&i.ServiceFee,
		&i.TotalPayable,
		&i.TermMonths,
		&i.StartDate,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listAgreementsByStudent = `-- name: ListAgreementsByStudent :many
SELECT id, student_id, invoice_id, principal, interest_rate, service_fee, total_payable, term_months, start_date, status, created_at FROM financing_agreements WHERE student_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListAgreementsByStudent(ctx context.Context, studentID pgtype.UUID) ([]FinancingAgreement, error) {
	rows, err := q.db.Query(ctx, listAgreementsByStudent, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FinancingAgreement
	for rows.Next() {
		var i FinancingAgreement
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.InvoiceID,
			&i.Principal,
			&i.InterestRate,
			&i.ServiceFee,
			&i.TotalPayable,
			&i.TermMonths,
			&i.StartDate,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInstallments = `-- name: ListInstallments :many
SELECT id, financing_id, installment_number, due_date, amount, status, created_at FROM monthly_installments WHERE financing_id = $1 ORDER BY installment_number
`

func (q *Queries) ListInstallments(ctx context.Context, financingID pgtype.UUID) ([]MonthlyInstallment, error) {
	rows, err := q.db.Query(ctx, listInstallments, financingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MonthlyInstallment
	for rows.Next() {
		var i MonthlyInstallment
		if err := rows.Scan(
			&i.ID,
			&i.FinancingID,
			&i.InstallmentNumber,
			&i.DueDate,
			&i.Amount,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
